repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - nextflow_schema.json
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: nf-core
  name: beav
  description: 10/23/2025 testing beav
  author: Ammon
  version: 2.0.0
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - nf_schema
    - gpu
  is_nfcore: true
